import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="flex flex-col min-h-screen justify-between">
          <header>
            <Navbar />
          </header>
          <main className=" mt-0 my-auto">{children}</main>
          <footer>
            <h1 className="font-bold py-2 bg-slate-600 text-stone-50 text-center">
              Next 13 Tutorial 2023
            </h1>
          </footer>
        </section>
      </body>
    </html>
  );
}
